CREATE TABLE IF NOT EXISTS "career_applications" (
	"id" serial PRIMARY KEY NOT NULL,
	"role" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"city" text NOT NULL,
	"state" text NOT NULL,
	"linkedin_url" text,
	"portfolio_url" text,
	"resume_object_key" text NOT NULL,
	"resume_file_name" text NOT NULL,
	"why_dapr" text NOT NULL,
	"relevant_experience" text NOT NULL,
	"role_specific_answer" text NOT NULL,
	"available_start" text NOT NULL,
	"authorized_to_work_us" boolean NOT NULL,
	"requires_sponsorship" boolean NOT NULL,
	"referral_source" text,
	"status" text DEFAULT 'new' NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text NOT NULL
);
