// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/services-page/CarGuy.tsx": () => import("../components/mockups/services-page/CarGuy.tsx"),
  "./components/mockups/services-page/Modern.tsx": () => import("../components/mockups/services-page/Modern.tsx"),
  "./components/mockups/services-page/UberMinimal.tsx": () => import("../components/mockups/services-page/UberMinimal.tsx")
};
